// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace FarmingGameplayTags
{
	FARMINGFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Test_1);
	FARMINGFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Test_2);
	FARMINGFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Test_3);
	FARMINGFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Test_4);

	FARMINGFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Test_11);
	FARMINGFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Test_12);
	FARMINGFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Test_13);
	FARMINGFRAMEWORK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Test_14);

}
